services:
  haproxy:
    image: haproxy:3.2.4-alpine
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./ssl/haproxy.pem:/usr/local/etc/haproxy/certs/haproxy.pem:ro
    networks:
      - app-network
  backend2:
    image: nginx:1.29.0-alpine
    container_name: backend2
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf:/etc/nginx
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
