services:
  haproxy:
    image: haproxy:3.2.4-alpine
    container_name: haproxy
    user: root
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./ssl/haproxy.pem:/usr/local/etc/haproxy/certs/haproxy.pem:ro
    network_mode: "host"
