services:
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy
    environment:
     - "ENVOY_UID=0"
    volumes:
     - ./ssl:/etc/certs:ro
     - ./envoy.yaml:/etc/envoy/envoy.yaml
    network_mode: "host"
